os: osx

language: c

compiler:
  - gcc

sudo: false

before_install:
  - brew update
  - brew upgrade pyenv
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv global 2.7.6
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash

script:
  - /bin/bash ~/build/gothraven/Get-Next-Line/tests/42FileChecker.sh --project "gnl" --path ~/build/gothraven/Get-Next-Line --no-norminette --no-update

after_success:
  - coveralls --exclude libft --exclude tests --gcov-options '\-lp'
  - make fclean
