language: c
sudo: false
script:
  - cd libft/
  - make
  - make clean
  - cd ..
  - gcc -Wall -Wextra -I get_next_line.h -c get_next_line.c
  - gcc -o get_next_line get_next_line.o libft/libft.a
  - ./get_next_line

