language: c
sudo: false
before_install:
  - pip install --user cpp-coveralls
script:
  - cd libft/
  - make
  - make clean
  - cd ..
  - gcc -Wall -Wextra -I get_next_line.h -c get_next_line.c
  - gcc -o get_next_line get_next_line.o libft/libft.a
  - ./get_next_line

after_success:
  - coveralls --exclude libft --exclude tests --gcov-options '\-lp'
